### ISSUE TITLE
Source has not been updated yet

### ISSUE THREAD

**Issue by GrayWolf64** [PoPenguin/sbox-ZZZ-Neko#2]
You are supposed to update your source repo apart from releasing a new version of your model.

**Comment by GrayWolf64** [comment]
It can be confusing because your repo only contains model & material files, so making a new release along side with the files which are the same as those in source repo is not necessary. You just need to update your source repo. You may put some announcements in release.

**Comment by PoPenguin** [comment]
okay,I'll fix it.

**Comment by GrayWolf64** [comment]
You can add tags to your repo to let more interested people see it.

**Comment by PoPenguin** [comment]
okay
